// AUTO-GENERADO (TUS02 i18n). Mapea el texto que envía el backend -> clave i18n BACKEND_ERRORS.*
// Si el backend cambia un texto, actualiza su entrada aquí.

/** Texto exacto del backend -> clave de traducción (bajo BACKEND_ERRORS). */
export const BACKEND_MSG: Readonly<Record<string, string>> = {
  "Calibración eliminada exitosamente": "CALIBRACION_ELIMINADA_EXITOSAMENTE",
  "Contraseña actualizada": "CONTRASENA_ACTUALIZADA",
  "Debe consumir de un lote de su cuenta": "DEBE_CONSUMIR_DE_UN_LOTE_DE_SU",
  "Debe usar un lote de su cuenta": "DEBE_USAR_UN_LOTE_DE_SU_CUENTA",
  "Debe vincular el lote a un proveedor de su cuenta": "DEBE_VINCULAR_EL_LOTE_A_UN_PROVEEDOR",
  "Debe vincular el perfil a un lote de su cuenta": "DEBE_VINCULAR_EL_PERFIL_A_UN_LOTE",
  "Debe vincular la entrada a un lote de su cuenta": "DEBE_VINCULAR_LA_ENTRADA_A_UN_LOTE",
  "El ID de la receta no coincide con el de la ruta": "EL_ID_DE_LA_RECETA_NO_COINCIDE",
  "El email del proveedor debe tener un formato válido": "EL_EMAIL_DEL_PROVEEDOR_DEBE_TENER_UN",
  "El email del proveedor no puede ser nulo o vacío": "EL_EMAIL_DEL_PROVEEDOR_NO_PUEDE_SER",
  "El email del proveedor no puede tener más de 100 caracteres": "EL_EMAIL_DEL_PROVEEDOR_NO_PUEDE_TENER",
  "El estado del lote no puede ser nulo o vacío": "EL_ESTADO_DEL_LOTE_NO_PUEDE_SER",
  "El estado del lote no puede tener más de 20 caracteres": "EL_ESTADO_DEL_LOTE_NO_PUEDE_TENER",
  "El lote de café no pertenece al usuario del perfil": "EL_LOTE_DE_CAFE_NO_PERTENECE_AL",
  "El lote no pertenece a su cuenta": "EL_LOTE_NO_PERTENECE_A_SU_CUENTA",
  "El método de procesamiento no puede ser nulo o vacío": "EL_METODO_DE_PROCESAMIENTO_NO_PUEDE_SER",
  "El método de procesamiento no puede tener más de 50 caracteres": "EL_METODO_DE_PROCESAMIENTO_NO_PUEDE_TENER",
  "El nombre de la receta no puede ser nulo o vacío": "EL_NOMBRE_DE_LA_RECETA_NO_PUEDE",
  "El nombre de la receta no puede tener más de 20 caracteres": "EL_NOMBRE_DE_LA_RECETA_NO_PUEDE_2",
  "El nombre del café no puede ser nulo o vacío": "EL_NOMBRE_DEL_CAFE_NO_PUEDE_SER",
  "El nombre del defecto no puede ser nulo o vacío": "EL_NOMBRE_DEL_DEFECTO_NO_PUEDE_SER",
  "El nombre del ingrediente no puede ser nulo o vacío": "EL_NOMBRE_DEL_INGREDIENTE_NO_PUEDE_SER",
  "El nombre del ingrediente no puede tener más de 100 caracteres": "EL_NOMBRE_DEL_INGREDIENTE_NO_PUEDE_TENER",
  "El nombre del lote de café no puede ser nulo o vacío": "EL_NOMBRE_DEL_LOTE_DE_CAFE_NO",
  "El nombre del lote de café no puede tener más de 100 caracteres": "EL_NOMBRE_DEL_LOTE_DE_CAFE_NO_2",
  "El nombre del perfil de tueste no puede ser nulo o vacío": "EL_NOMBRE_DEL_PERFIL_DE_TUESTE_NO",
  "El nombre del perfil de tueste no puede tener más de 50 caracteres": "EL_NOMBRE_DEL_PERFIL_DE_TUESTE_NO_2",
  "El nombre del proveedor debe tener entre 2 y 100 caracteres": "EL_NOMBRE_DEL_PROVEEDOR_DEBE_TENER_ENTRE",
  "El nombre del proveedor no puede contener solo números": "EL_NOMBRE_DEL_PROVEEDOR_NO_PUEDE_CONTENER",
  "El nombre del proveedor no puede ser nulo o vacío": "EL_NOMBRE_DEL_PROVEEDOR_NO_PUEDE_SER",
  "El nombre del proveedor solo puede contener letras, espacios y tildes": "EL_NOMBRE_DEL_PROVEEDOR_SOLO_PUEDE_CONTENER",
  "El origen del café no puede ser nulo o vacío": "EL_ORIGEN_DEL_CAFE_NO_PUEDE_SER",
  "El origen del café no puede tener más de 100 caracteres": "EL_ORIGEN_DEL_CAFE_NO_PUEDE_TENER",
  "El producto final no puede ser nulo o vacío": "EL_PRODUCTO_FINAL_NO_PUEDE_SER_NULO",
  "El producto final no puede tener más de 100 caracteres": "EL_PRODUCTO_FINAL_NO_PUEDE_TENER_MAS",
  "El producto final solo puede contener letras, números y espacios": "EL_PRODUCTO_FINAL_SOLO_PUEDE_CONTENER_LETRAS",
  "El registro ya está anulado": "EL_REGISTRO_YA_ESTA_ANULADO",
  "El tipo de café no puede ser nulo o vacío": "EL_TIPO_DE_CAFE_NO_PUEDE_SER",
  "El tipo de café no puede tener más de 50 caracteres": "EL_TIPO_DE_CAFE_NO_PUEDE_TENER",
  "El tipo de defecto no puede ser nulo o vacío": "EL_TIPO_DE_DEFECTO_NO_PUEDE_SER",
  "El tipo de tueste no puede ser nulo o vacío": "EL_TIPO_DE_TUESTE_NO_PUEDE_SER",
  "Error interno del servidor": "ERROR_INTERNO_DEL_SERVIDOR",
  "La causa probable no puede ser nula o vacía": "LA_CAUSA_PROBABLE_NO_PUEDE_SER_NULA",
  "La duración debe ser un valor positivo": "LA_DURACION_DEBE_SER_UN_VALOR_POSITIVO",
  "La duración no puede exceder 1440 minutos (24 horas)": "LA_DURACION_NO_PUEDE_EXCEDER_1440_MINUTOS",
  "La fecha de uso es requerida": "LA_FECHA_DE_USO_ES_REQUERIDA",
  "La fecha de uso no puede ser anterior a un año desde hoy": "LA_FECHA_DE_USO_NO_PUEDE_SER",
  "La fecha de uso no puede ser posterior a 5 años desde hoy": "LA_FECHA_DE_USO_NO_PUEDE_SER_2",
  "La región del café no puede ser nula o vacía": "LA_REGION_DEL_CAFE_NO_PUEDE_SER",
  "La solución sugerida no puede ser nula o vacía": "LA_SOLUCION_SUGERIDA_NO_PUEDE_SER_NULA",
  "La temperatura debe estar entre 0 y 300°C": "LA_TEMPERATURA_DEBE_ESTAR_ENTRE_0_Y",
  "La temperatura no puede ser nula": "LA_TEMPERATURA_NO_PUEDE_SER_NULA",
  "La ubicación del proveedor debe tener entre 2 y 200 caracteres": "LA_UBICACION_DEL_PROVEEDOR_DEBE_TENER_ENTRE",
  "La ubicación del proveedor no puede contener solo comas, puntos o punto y coma": "LA_UBICACION_DEL_PROVEEDOR_NO_PUEDE_CONTENER",
  "La ubicación del proveedor no puede contener solo números": "LA_UBICACION_DEL_PROVEEDOR_NO_PUEDE_CONTENER_2",
  "La ubicación del proveedor no puede ser nula o vacía": "LA_UBICACION_DEL_PROVEEDOR_NO_PUEDE_SER",
  "La ubicación del proveedor solo puede contener letras, números, espacios, tildes, comas, puntos y punto y coma": "LA_UBICACION_DEL_PROVEEDOR_SOLO_PUEDE_CONTENER",
  "La variedad del café no puede ser nula o vacía": "LA_VARIEDAD_DEL_CAFE_NO_PUEDE_SER",
  "Lote de café eliminado exitosamente": "LOTE_DE_CAFE_ELIMINADO_EXITOSAMENTE",
  "Lote no encontrado": "LOTE_NO_ENCONTRADO",
  "No autorizado o receta no encontrada": "NO_AUTORIZADO_O_RECETA_NO_ENCONTRADA",
  "No autorizado para anular este registro": "NO_AUTORIZADO_PARA_ANULAR_ESTE_REGISTRO",
  "No autorizado para consultar este lote": "NO_AUTORIZADO_PARA_CONSULTAR_ESTE_LOTE",
  "No autorizado para consultar lotes de este proveedor": "NO_AUTORIZADO_PARA_CONSULTAR_LOTES_DE_ESTE",
  "No autorizado para consultar perfiles de este lote": "NO_AUTORIZADO_PARA_CONSULTAR_PERFILES_DE_ESTE",
  "No autorizado para eliminar esta entrada": "NO_AUTORIZADO_PARA_ELIMINAR_ESTA_ENTRADA",
  "No autorizado para eliminar este lote": "NO_AUTORIZADO_PARA_ELIMINAR_ESTE_LOTE",
  "No autorizado para eliminar este perfil": "NO_AUTORIZADO_PARA_ELIMINAR_ESTE_PERFIL",
  "No autorizado para eliminar este proveedor": "NO_AUTORIZADO_PARA_ELIMINAR_ESTE_PROVEEDOR",
  "No autorizado para eliminar este registro": "NO_AUTORIZADO_PARA_ELIMINAR_ESTE_REGISTRO",
  "No autorizado para modificar esta entrada": "NO_AUTORIZADO_PARA_MODIFICAR_ESTA_ENTRADA",
  "No autorizado para modificar este lote": "NO_AUTORIZADO_PARA_MODIFICAR_ESTE_LOTE",
  "No autorizado para modificar este perfil": "NO_AUTORIZADO_PARA_MODIFICAR_ESTE_PERFIL",
  "No autorizado para modificar este proveedor": "NO_AUTORIZADO_PARA_MODIFICAR_ESTE_PROVEEDOR",
  "No autorizado para modificar este registro": "NO_AUTORIZADO_PARA_MODIFICAR_ESTE_REGISTRO",
  "No autorizado para ver esta entrada": "NO_AUTORIZADO_PARA_VER_ESTA_ENTRADA",
  "No autorizado para ver este lote": "NO_AUTORIZADO_PARA_VER_ESTE_LOTE",
  "No autorizado para ver este perfil": "NO_AUTORIZADO_PARA_VER_ESTE_PERFIL",
  "No autorizado para ver este proveedor": "NO_AUTORIZADO_PARA_VER_ESTE_PROVEEDOR",
  "No autorizado para ver este registro": "NO_AUTORIZADO_PARA_VER_ESTE_REGISTRO",
  "No puede consultar entradas de otro perfil": "NO_PUEDE_CONSULTAR_ENTRADAS_DE_OTRO_PERFIL",
  "No puede consultar lotes de otro perfil": "NO_PUEDE_CONSULTAR_LOTES_DE_OTRO_PERFIL",
  "No puede consultar perfiles de otro perfil": "NO_PUEDE_CONSULTAR_PERFILES_DE_OTRO_PERFIL",
  "No puede consultar proveedores de otro perfil": "NO_PUEDE_CONSULTAR_PROVEEDORES_DE_OTRO_PERFIL",
  "No se pudo actualizar el portafolio": "NO_SE_PUDO_ACTUALIZAR_EL_PORTAFOLIO",
  "No se pudo actualizar el stock del lote": "NO_SE_PUDO_ACTUALIZAR_EL_STOCK_DEL",
  "No se pudo crear el defecto": "NO_SE_PUDO_CREAR_EL_DEFECTO",
  "No se pudo crear el ingrediente": "NO_SE_PUDO_CREAR_EL_INGREDIENTE",
  "No se pudo crear el lote de café": "NO_SE_PUDO_CREAR_EL_LOTE_DE",
  "No se pudo crear el perfil de tueste": "NO_SE_PUDO_CREAR_EL_PERFIL_DE",
  "No se pudo crear el portafolio": "NO_SE_PUDO_CREAR_EL_PORTAFOLIO",
  "No se pudo crear el proveedor": "NO_SE_PUDO_CREAR_EL_PROVEEDOR",
  "No se pudo crear el registro": "NO_SE_PUDO_CREAR_EL_REGISTRO",
  "No se pudo crear la calibración": "NO_SE_PUDO_CREAR_LA_CALIBRACION",
  "No se pudo crear la entrada de inventario": "NO_SE_PUDO_CREAR_LA_ENTRADA_DE",
  "No se pudo crear la receta. Intente de nuevo.": "NO_SE_PUDO_CREAR_LA_RECETA_INTENTE",
  "No se pudo crear la sesión": "NO_SE_PUDO_CREAR_LA_SESION",
  "No se pudo obtener el ingrediente creado": "NO_SE_PUDO_OBTENER_EL_INGREDIENTE_CREADO",
  "No se pudo obtener el lote de café creado": "NO_SE_PUDO_OBTENER_EL_LOTE_DE",
  "No se pudo obtener el perfil de tueste creado": "NO_SE_PUDO_OBTENER_EL_PERFIL_DE",
  "No se pudo obtener el portafolio creado": "NO_SE_PUDO_OBTENER_EL_PORTAFOLIO_CREADO",
  "No se pudo obtener el proveedor creado": "NO_SE_PUDO_OBTENER_EL_PROVEEDOR_CREADO",
  "No se puede modificar un registro anulado": "NO_SE_PUEDE_MODIFICAR_UN_REGISTRO_ANULADO",
  "No se pueden repetir especialidades": "NO_SE_PUEDEN_REPETIR_ESPECIALIDADES",
  "No se pueden tener más de 4 especialidades": "NO_SE_PUEDEN_TENER_MAS_DE_4",
  "Phone debe tener entre 7 y 15 dígitos": "PHONE_DEBE_TENER_ENTRE_7_Y_15",
  "Proveedor eliminado exitosamente": "PROVEEDOR_ELIMINADO_EXITOSAMENTE",
  "Sesión no válida": "SESION_NO_VALIDA",
  "Tipo de tueste no válido. Debe ser: Ligero, Medio, Medio-Oscuro, Oscuro": "TIPO_DE_TUESTE_NO_VALIDO_DEBE_SER",
  "Usuario no autenticado o perfil no encontrado": "USUARIO_NO_AUTENTICADO_O_PERFIL_NO_ENCONTRADO",
  "Ya existe un café con ese nombre": "YA_EXISTE_UN_CAFE_CON_ESE_NOMBRE",
  "Cada especialidad debe tener entre 2 y 100 caracteres": "CADA_ESPECIALIDAD_DEBE_TENER_ENTRE_2_Y",
  "Cada especialidad solo puede contener letras, espacios y tildes; no puede ser solo números ni solo signos de puntuación": "CADA_ESPECIALIDAD_SOLO_PUEDE_CONTENER_LETRAS_ESP",
  "Correo inválido": "CORREO_INVALIDO",
  "Debe indicar si es favorito": "DEBE_INDICAR_SI_ES_FAVORITO",
  "Debe seleccionar un lote": "DEBE_SELECCIONAR_UN_LOTE",
  "Debe seleccionar un proveedor": "DEBE_SELECCIONAR_UN_PROVEEDOR",
  "Debe vincular un lote de café": "DEBE_VINCULAR_UN_LOTE_DE_CAFE",
  "El correo es obligatorio": "EL_CORREO_ES_OBLIGATORIO",
  "El estado es obligatorio": "EL_ESTADO_ES_OBLIGATORIO",
  "El estado no puede superar 20 caracteres": "EL_ESTADO_NO_PUEDE_SUPERAR_20_CARACTERES",
  "El motivo es obligatorio": "EL_MOTIVO_ES_OBLIGATORIO",
  "El motivo no puede superar 25 caracteres": "EL_MOTIVO_NO_PUEDE_SUPERAR_25_CARACTERES",
  "El método de procesamiento es obligatorio": "EL_METODO_DE_PROCESAMIENTO_ES_OBLIGATORIO",
  "El método de procesamiento no puede superar 50 caracteres": "EL_METODO_DE_PROCESAMIENTO_NO_PUEDE_SUPERAR",
  "El nombre del café no puede superar 255 caracteres.": "EL_NOMBRE_DEL_CAFE_NO_PUEDE_SUPERAR",
  "El nombre del defecto no puede superar 255 caracteres.": "EL_NOMBRE_DEL_DEFECTO_NO_PUEDE_SUPERAR",
  "El nombre del lote es obligatorio": "EL_NOMBRE_DEL_LOTE_ES_OBLIGATORIO",
  "El nombre del lote no puede superar 100 caracteres": "EL_NOMBRE_DEL_LOTE_NO_PUEDE_SUPERAR",
  "El nombre es obligatorio": "EL_NOMBRE_ES_OBLIGATORIO",
  "El nombre no puede contener caracteres especiales": "EL_NOMBRE_NO_PUEDE_CONTENER_CARACTERES_ESPECIALE",
  "El nombre no puede contener números ni caracteres especiales": "EL_NOMBRE_NO_PUEDE_CONTENER_NUMEROS_NI",
  "El nombre no puede superar 50 caracteres": "EL_NOMBRE_NO_PUEDE_SUPERAR_50_CARACTERES",
  "El origen es obligatorio": "EL_ORIGEN_ES_OBLIGATORIO",
  "El origen no puede superar 100 caracteres": "EL_ORIGEN_NO_PUEDE_SUPERAR_100_CARACTERES",
  "El peso admite máximo 2 decimales": "EL_PESO_ADMITE_MAXIMO_2_DECIMALES",
  "El peso del defecto debe ser mayor que cero.": "EL_PESO_DEL_DEFECTO_DEBE_SER_MAYOR",
  "El peso es obligatorio": "EL_PESO_ES_OBLIGATORIO",
  "El peso máximo es 70 kg": "EL_PESO_MAXIMO_ES_70_KG",
  "El peso mínimo es 1 kg": "EL_PESO_MINIMO_ES_1_KG",
  "El peso total del café no puede ser negativo.": "EL_PESO_TOTAL_DEL_CAFE_NO_PUEDE",
  "El porcentaje debe estar entre 0 y 100.": "EL_PORCENTAJE_DEBE_ESTAR_ENTRE_0_Y",
  "El producto final es obligatorio": "EL_PRODUCTO_FINAL_ES_OBLIGATORIO",
  "El producto final no puede superar 100 caracteres": "EL_PRODUCTO_FINAL_NO_PUEDE_SUPERAR_100",
  "El tipo de café es obligatorio": "EL_TIPO_DE_CAFE_ES_OBLIGATORIO",
  "El tipo de café no puede superar 50 caracteres": "EL_TIPO_DE_CAFE_NO_PUEDE_SUPERAR",
  "El tipo de defecto no puede superar 255 caracteres.": "EL_TIPO_DE_DEFECTO_NO_PUEDE_SUPERAR",
  "El tipo es obligatorio": "EL_TIPO_ES_OBLIGATORIO",
  "El tipo no puede superar 20 caracteres": "EL_TIPO_NO_PUEDE_SUPERAR_20_CARACTERES",
  "Email debe tener un formato válido": "EMAIL_DEBE_TENER_UN_FORMATO_VALIDO",
  "Email es requerido": "EMAIL_ES_REQUERIDO",
  "Email no puede tener más de 100 caracteres": "EMAIL_NO_PUEDE_TENER_MAS_DE_100",
  "Indique el nombre del café.": "INDIQUE_EL_NOMBRE_DEL_CAFE",
  "Indique la solución sugerida.": "INDIQUE_LA_SOLUCION_SUGERIDA",
  "Indique la variedad del café.": "INDIQUE_LA_VARIEDAD_DEL_CAFE",
  "La altitud debe ser al menos 0 msnm": "LA_ALTITUD_DEBE_SER_AL_MENOS_0",
  "La altitud es obligatoria": "LA_ALTITUD_ES_OBLIGATORIA",
  "La altitud no puede superar 2500 msnm": "LA_ALTITUD_NO_PUEDE_SUPERAR_2500_MSNM",
  "La cantidad (kg) es obligatoria": "LA_CANTIDAD_KG_ES_OBLIGATORIA",
  "La cantidad consumida es obligatoria": "LA_CANTIDAD_CONSUMIDA_ES_OBLIGATORIA",
  "La cantidad debe ser mayor que cero": "LA_CANTIDAD_DEBE_SER_MAYOR_QUE_CERO",
  "La contraseña actual es obligatoria": "LA_CONTRASENA_ACTUAL_ES_OBLIGATORIA",
  "La contraseña debe incluir al menos una mayúscula, una minúscula, un número y un carácter especial (@$!%*?&_-#)": "LA_CONTRASENA_DEBE_INCLUIR_AL_MENOS_UNA",
  "La contraseña debe tener entre 6 y 120 caracteres": "LA_CONTRASENA_DEBE_TENER_ENTRE_6_Y",
  "La contraseña debe tener entre 8 y 120 caracteres": "LA_CONTRASENA_DEBE_TENER_ENTRE_8_Y",
  "La contraseña es obligatoria": "LA_CONTRASENA_ES_OBLIGATORIA",
  "La duración es obligatoria": "LA_DURACION_ES_OBLIGATORIA",
  "La duración mínima es 1 minuto": "LA_DURACION_MINIMA_ES_1_MINUTO",
  "La duración no puede superar 15 minutos": "LA_DURACION_NO_PUEDE_SUPERAR_15_MINUTOS",
  "La especialidad no puede estar vacía": "LA_ESPECIALIDAD_NO_PUEDE_ESTAR_VACIA",
  "La fecha es obligatoria": "LA_FECHA_ES_OBLIGATORIA",
  "La moneda es obligatoria": "LA_MONEDA_ES_OBLIGATORIA",
  "La nueva contraseña debe incluir al menos una mayúscula, una minúscula, un número y un carácter especial (@$!%*?&_-#)": "LA_NUEVA_CONTRASENA_DEBE_INCLUIR_AL_MENOS",
  "La nueva contraseña debe tener entre 8 y 120 caracteres": "LA_NUEVA_CONTRASENA_DEBE_TENER_ENTRE_8",
  "La nueva contraseña es obligatoria": "LA_NUEVA_CONTRASENA_ES_OBLIGATORIA",
  "La región no puede superar 255 caracteres.": "LA_REGION_NO_PUEDE_SUPERAR_255_CARACTERES",
  "La temperatura final debe ser al menos 1 °C": "LA_TEMPERATURA_FINAL_DEBE_SER_AL_MENOS",
  "La temperatura final debe ser un número entero": "LA_TEMPERATURA_FINAL_DEBE_SER_UN_NUMERO",
  "La temperatura final es obligatoria": "LA_TEMPERATURA_FINAL_ES_OBLIGATORIA",
  "La temperatura final no puede superar 240 °C": "LA_TEMPERATURA_FINAL_NO_PUEDE_SUPERAR_240",
  "La temperatura inicial debe ser al menos 1 °C": "LA_TEMPERATURA_INICIAL_DEBE_SER_AL_MENOS",
  "La temperatura inicial debe ser un número entero": "LA_TEMPERATURA_INICIAL_DEBE_SER_UN_NUMERO",
  "La temperatura inicial es obligatoria": "LA_TEMPERATURA_INICIAL_ES_OBLIGATORIA",
  "La temperatura inicial no puede superar 240 °C": "LA_TEMPERATURA_INICIAL_NO_PUEDE_SUPERAR_240",
  "La variedad no puede superar 255 caracteres.": "LA_VARIEDAD_NO_PUEDE_SUPERAR_255_CARACTERES",
  "Location debe tener entre 2 y 200 caracteres": "LOCATION_DEBE_TENER_ENTRE_2_Y_200",
  "Location es requerido": "LOCATION_ES_REQUERIDO",
  "Location solo puede contener letras, números, espacios, tildes, comas, puntos y punto y coma; no puede ser solo números ni solo signos de puntuación": "LOCATION_SOLO_PUEDE_CONTENER_LETRAS_NUMEROS_ESPA",
  "Lote inválido": "LOTE_INVALIDO",
  "Name debe tener entre 2 y 100 caracteres": "NAME_DEBE_TENER_ENTRE_2_Y_100",
  "Name es requerido": "NAME_ES_REQUERIDO",
  "Name solo puede contener letras, espacios y tildes.": "NAME_SOLO_PUEDE_CONTENER_LETRAS_ESPACIOS_Y",
  "Phone debe contener solo números enteros y máximo 15 dígitos": "PHONE_DEBE_CONTENER_SOLO_NUMEROS_ENTEROS_Y",
  "Phone debe ser positivo": "PHONE_DEBE_SER_POSITIVO",
  "Phone debe tener al menos 7 dígitos": "PHONE_DEBE_TENER_AL_MENOS_7_DIGITOS",
  "Phone es requerido": "PHONE_ES_REQUERIDO",
  "Proveedor inválido": "PROVEEDOR_INVALIDO",
};

/** Mensajes dinámicos: se comparan por prefijo (el backend concatena un valor). */
export const BACKEND_MSG_PREFIX: ReadonlyArray<readonly [string, string]> = [
  ["Categoría de extracción no válida:", "PREFIX_CATEGORIA_DE_EXTRACCION_NO_VALIDA"],
  ["Método de extracción no válido:", "PREFIX_METODO_DE_EXTRACCION_NO_VALIDO"],
  ["El estado del lote debe ser uno de:", "PREFIX_EL_ESTADO_DEL_LOTE_DEBE_SER_UNO"],
  ["El método de procesamiento debe ser uno de:", "PREFIX_EL_METODO_DE_PROCESAMIENTO_DEBE_SER_UNO"],
  ["El tipo de café debe ser uno de:", "PREFIX_EL_TIPO_DE_CAFE_DEBE_SER_UNO"],
  ["No se pudo leer el JSON:", "PREFIX_NO_SE_PUDO_LEER_EL_JSON"],
  ["Ya existe una receta con el nombre", "PREFIX_YA_EXISTE_UNA_RECETA_CON_EL_NOMBRE"],
  ["El portafolio indicado no existe o no pertenece a su perfil", "PREFIX_EL_PORTAFOLIO_INDICADO_NO_EXISTE_O_NO"],
  ["La sesión de cata indicada no existe o no pertenece a su perfil", "PREFIX_LA_SESION_DE_CATA_INDICADA_NO_EXISTE"],
];
